apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: environment
    objref:
      kind: ConfigMap
      name: app2-us1-prod
      apiVersion: v1
      fieldref:
        fieldpath: data.environment
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: app2-us1-prod
    literals:
      - environment=us1-prod
