apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -prod

patches:
  - target:
      kind: Deployment
      name: app1
    patch: deployment-patch.yaml