apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps
spec:
  generators:
  - git:
      repoURL: https://github.com/mariocalipo/argocd.git
      revision: HEAD
      directories:
      - path: app1/envs/*
  template:
    metadata:
      name: '{{path[0]}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mariocalipo/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          forceSync: true 