apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-projects
spec:
  generators:
  - git:
      repoURL: https://github.com/mariocalipo/argocd.git
      revision: HEAD
      directories:
      - path: apps/**/* 
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mariocalipo/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'