apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-app
  namespace: argocd  # Namespace where ArgoCD is installed
spec:
  project: default  # ArgoCD project to which the application belongs
  source:
    repoURL: https://charts.helm.sh/stable  # Official Helm charts repository URL for Istio
    chart: istio-base  # Name of the Istio base chart in the repository
    version: 1.16.1  # Version of the Istio chart to install
    targetRevision: main  # Branch or commit hash in the repository (not needed for official Helm charts repository)
    helm:
      valueFiles:
        - values.yaml  # Path to your values.yaml file for Istio configuration
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL
    namespace: istio-system  # Namespace where Istio will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      forceSync: true
    syncOptions:
      - CreateNamespace=true