apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd  # Namespace where ArgoCD is installed
spec:
  project: default  # ArgoCD project to which the application belongs
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts  # Official Helm charts repository URL for Istio
    chart: base  # Name of the Istio base chart in the repository
    version: 1.21.0  # Version of the Istio chart to install
    targetRevision: 1.21.0
    helm:
      valueFiles:
        - values.yaml  # Path to your values.yaml file for Istio configuration
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL
    namespace: istio-system  # Namespace where Istio will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      forceSync: true
    syncOptions:
      - CreateNamespace=true