apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common
  - ../apps/app1/us1/dev
  - ../apps/app1/us1/prod
  - ../apps/app1/us1/stage
  - ../apps/app1/us1/uat
  - ../apps/app2/us1/dev
  - ../apps/app2/us1/prod
  - ../apps/app2/us1/stage
  - ../apps/app2/us1/uat