apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
vars:
  - name: environment
    objref:
      kind: ConfigMap
      name: app1-us1-dev
      apiVersion: v1
    fieldref:
      fieldpath: data.environment
resources:
  - ../../main/common/deployment.yaml
  - ../../main/common/service.yaml
  - ../../main/common/ingress.yaml
configMapGenerator:
  - name: app1-us1-dev
    literals:
      - environment=us1-dev