apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
namePrefix: app1-

patches:
  - target:
      kind: Ingress
      name: ingress
    patch: |-
      - op: replace
        path: /spec/defaultBackend/service/name
        value: app1-ingress-dev
    namePrefix: ""
    nameSuffix: ""